ProyectoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from postApp.views import inicio

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name="inicio"),
    path('postApp/', include('postApp.urls')),
    path('usuariosApp/', include('usuariosApp.urls'))
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= staticfiles_urlpatterns()

postApp/urls.py
from django.urls import path
from postApp import views

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('aboutUs/', views.aboutUs, name='AboutUs'),
    path('postLista/', views.ListaPosts.as_view(), name='postLista'),
    path('verPost/<pk>/', views.VerPost.as_view(), name='verPost'),
    path('crearPost/', views.CrearPost.as_view(), name='crearPost'),
    path('editarPost/<pk>/', views.UpdatePost.as_view(), name='editarPost'),
    path('borrarPost/<pk>/', views.BorrarPost.as_view(), name='borrarPost'),
    path('verPost/<pk>/comentar/',views.AgregarComentario.as_view(), name='comentar'),
    path('like/<pk>', views.meGusta, name='likePost'),
    path('contacto/',views.contact, name='Contacto'),
    path('testing/',views.testing,name='CategoriaTesting'),
    path('Lenguajes/',views.Lenguajes,name='Lenguajes'),
    path('MachineLearning/',views.machine_learning,name='MachineLearning'),
    path('noticiasit/',views.noticias_it,name='NoticiasIT'),
]

postApp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField



class Categoria(models.Model):
    nombre = models.CharField(
        'categoria', max_length=100, null=False, blank=False)

    def __str__(self):
        return self.nombre


class Post(models.Model):
    titulo = models.CharField('titulo', max_length=500, null=False, blank=False)
    subtitulo = models.CharField(
        'subtitulo', max_length=500, null=False, blank=False)
    contenido = RichTextField('contenido', null=False, blank=False)
    imagen = models.ImageField(
        upload_to='imagenes_post', null=True, blank=True)
    categoria = models.ForeignKey(Categoria,  on_delete=models.DO_NOTHING)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    # Agrega fecha de origen del post:
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    # Agrega fecha y actualiza segun la fecha de la edicion:
    fecha_edicion = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='likes_posts')

    def __str__(self):
        return f'{self.titulo} - Autor: {self.autor}'

    def delete(self, *args, **kwargs):
        self.imagen.delete()
        super().delete(args, kwargs)

    def total_likes(self):
        return self.likes.count()

    @property
    def get_comentarios_count(self):
        return self.comentarios.all().count()

class Comentario(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(
        Post, related_name="comentarios", on_delete=models.CASCADE)
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    contenido = models.TextField('contenido', null=False, blank=False)

    def __str__(self):
        return f'{self.autor}'

postApp/forms.py
from django import forms
from .models import Post, Comentario

#Formulario contacto para enviar email
class ContactEmailForm(forms.Form):
    first_name = forms.CharField(max_length = 50)
    last_name = forms.CharField(max_length = 50)
    email_address = forms.EmailField(max_length = 150)
    message = forms.CharField(widget = forms.Textarea, max_length = 2000)

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('contenido',)

class PostForm(forms.ModelForm):
        class Meta:
            model = Post
            fields = ('titulo', 'subtitulo', 'categoria', 'autor', 'contenido', 'imagen')
        
            widgets = {
            'titulo': forms.TextInput(attrs={'class':'form-control','placeholder':'Titulo'}),
            'subtitulo': forms.TextInput(attrs={'class':'form-control','placeholder':'Subtitulo'}),
            'autor' : forms.TextInput(attrs={'class':'form-control','value':'','id':'autor', 'type':'hidden'}),
        }
        

postApp/views.py
#Funcionalidades de los post
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from postApp.models import Post, Comentario
from django.db.models import Q
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from postApp.forms import ComentarioForm, PostForm
from django.core.paginator import Paginator, EmptyPage

#Import para enviar correos
from postApp.forms import ContactEmailForm
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect

def inicio(request):
    queryset = request.GET.get("buscar")
    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(subtitulo__icontains = queryset)
        ).distinct()
        return render(request, 'postApp/inicio.html', {'posts': posts})
    else:
        todosLosPosts = Post.objects.all().order_by('-fecha_publicacion')
        mostrar = Paginator(todosLosPosts, 3)
        pagina_num = request.GET.get('pagina', 1)
        try:
            posts = mostrar.page(pagina_num)
            numeros = "n" * posts.paginator.num_pages
        except EmptyPage:
            posts = mostrar.page(1)
            numeros = "n" * posts.paginator.num_pages
        return render(request, 'postApp/inicio.html', {'posts': posts, 'numeros': numeros})


class ListaPosts(ListView):

    model = Post
    template_name= "postApp/lista_post.html"
    ordering = ['-fecha_publicacion']

class VerPost(DetailView):
    
    model = Post
    template_name= "postApp/ver_post.html"

    def get_context_data(self,*args, **kwargs):
        contexto= super(VerPost, self).get_context_data(*args, **kwargs)
        numero = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = numero.total_likes()
        contexto['total_likes']= total_likes
        return contexto

class CrearPost(CreateView):

    model = Post
    form_class= PostForm    
    success_url = "/postApp/postLista"

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto.update({
            'tipo_template': 'Publicar'
        })
        return contexto
class UpdatePost(UpdateView):

    model = Post
    form_class= PostForm 
    success_url = "/postApp/postLista"

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto.update({
            'tipo_template': 'Editar' 
        })
        return contexto
class BorrarPost(DeleteView):

    model = Post
    success_url = "/postApp/postLista"

class AgregarComentario(CreateView):
    
    model = Comentario
    form_class = ComentarioForm
    template_name = "postApp/comentario_form.html"

    def form_valid(self,form):
        form.instance.post_id = self.kwargs['pk']
        form.instance.autor = self.request.user
        return super().form_valid(form)
    
    success_url = "/"

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto.update({
            'tipo_template': 'Comentar'
        })
        return contexto


def meGusta(request,pk):
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        post.likes.add(request.user)
        return HttpResponseRedirect(reverse('verPost', args=pk))

def testing(request):
    queryset = request.GET.get("buscar")
    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(subtitulo__icontains = queryset)
        ).distinct()
        return render(request, 'postApp/inicio.html', {'posts': posts})
    else:
        posts=Post.objects.filter(categoria__nombre = 'Testing')
        return render(request,'postApp/categoria_testing.html',{'posts':posts})
    
def Lenguajes(request):
    queryset = request.GET.get("buscar")
    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(subtitulo__icontains = queryset)
        ).distinct()
        return render(request, 'postApp/inicio.html', {'posts': posts})
    else:    
        posts=Post.objects.filter(categoria__nombre = 'Lenguajes')
        return render(request,'postApp/categoria_testing.html',{'posts':posts})

def machine_learning(request):
    queryset = request.GET.get("buscar")
    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(subtitulo__icontains = queryset)
        ).distinct()
        return render(request, 'postApp/inicio.html', {'posts': posts})
    else:    
        posts=Post.objects.filter(categoria__nombre = 'MachineLearning')
        return render(request,'postApp/categoria_testing.html',{'posts':posts})

def noticias_it(request):
    queryset = request.GET.get("buscar")
    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(subtitulo__icontains = queryset)
        ).distinct()
        return render(request, 'postApp/inicio.html', {'posts': posts})
    else:    
        posts=Post.objects.filter(categoria__nombre = 'Noticias IT')
        return render(request,'postApp/categoria_testing.html',{'posts':posts})

def aboutUs(request):
    return render(request,'postApp/about_us.html')

#Envio de correo desde Contacto
def contact(request):
    if request.method == 'POST':
        form = ContactEmailForm(request.POST)
        if form.is_valid():
            subject = "Tienes una nueva consulta desde el blog CoderHouse" 
            body = {
            'first_name': form.cleaned_data['first_name'], 
            'last_name': form.cleaned_data['last_name'], 
            'email': form.cleaned_data['email_address'], 
            'message':form.cleaned_data['message'], 
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'willyeleno44@gmail.com', ['willyeleno44@gmail.com']) 
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return render(request, "usuariosApp/bienvenido.html", {"mensaje": "Tu correo ha sido enviado con éxito. En al menos 48 horas nuestro equipo de soporte te va a contactar."})

    form = ContactEmailForm()
    return render(request, "postApp/contacto.html", {'form':form})

templates/postApp/categoria_testing.html
{% extends 'index.html' %}

{% block barraBusqueda %}

<div class="row" style="width: 400px">
  <div class="col-md-12 search">
    <form method="get">
        <div id="custom-search-input">
          <div class="input-group col-md-12">
            <input type="text" class="form-control" style="height: 29px" placeholder="Buscar..." name="buscar" value = "{{ request.GET.buscar }}">
            <span class="input-group-list">
              <i class="icon icon-search"></i>
              <button type="submit" class="boton btn-success">Buscar</button>
            </span>
          </div>
        </div>
    </form>
  </div>
</div>

{% endblock barraBusqueda %}


{% block bienvenido %}

<h1 class="fw-bolder">¡Bienvenidos al Blog de CoderHouse!</h1>



{% endblock bienvenido %}




{% block editNavBar %}


{% if not request.user.is_authenticated  %}

<li class="nav-item"><a class="nav-link" href="{% url 'AboutUs' %}">Acerca de nosotros</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Contacto' %}">Contactanos</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Login' %}">Ingresar</a></li>
    
{% endif %}
    

{% if request.user.is_authenticated %}

<li class="nav-item"><a class="nav-link" href="{% url 'AboutUs' %}">Acerca de nosotros</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Contacto' %}">Contactanos</a></li>
<div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Hola, {{request.user}}
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
          {% if perms.postApp.add_post %}
          <li><a class="dropdown-item" href="{% url 'postLista' %}">Administrar Posts</a></li>
            {% endif %}
          <li><a class="dropdown-item" href="{% url 'PostsConMeGustaPropios' %}">Mi actividad | Me Gusta</a></li>
          <li><a class="dropdown-item" href="{% url 'EditarPerfil' %}">Editar Perfil</a></li>
          <li><a class="dropdown-item" href="{% url 'Logout' %}">Cerrar Sesión</a></li>
        </ul>
      </li>
    </ul>
  </div>

{% endif %}

{% endblock editNavBar %}


{% block logInLogOut %}
    
<h1>{{mensaje}}</h1>

{% endblock logInLogOut %}

{% block backgroundImage %}

<div
    class="bg-image"
    style="
    background-image: url('/static/css/images/Blog-Post_thumbnail.png');
    height: 70vh;
    "
></div>

{% endblock backgroundImage %}


{% block blockPosts %}


{% if posts %}

{% for p in posts %}
<div class="container">
  <div class="row mb-2">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-primary">{{ p.categoria }}</strong>
              <h3 class="mb-0">{{ p.titulo }}</h3>
              <div class="mb-1 text-muted">{{p.fecha_publicacion}}|{{p.autor}}</div>
              <p class="card-text mb-auto">{{ p.subtitulo }}</p>
                <span><i class="fa-regular fa-thumbs-up"></i> {{ p.likes.count }}</span>
                <span><i class="fa-regular fa-comments"></i> {{ p.get_comentarios_count }}</span>
            <a href="{% url 'verPost' p.id %}">Ver post</a>
        </div>
      <div class="col-auto d-none d-lg-block">
          <img src="{{ p.imagen.url }}" width="250" height="250">
      </div>
    </div>
  </div>    
</div> 
{% endfor %}
    
{% endif %}
    
  
{% endblock blockPosts %}

templates/postApp/comentario_form.html
{% extends 'index.html' %}


{% block editNavBar %}
                        
{% if not request.user.is_authenticated  %}

<li class="nav-item"><a class="nav-link" href="{% url 'AboutUs' %}">Acerca de nosotros</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Contacto' %}">Contactanos</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Login' %}">Ingresar</a></li>
    
{% endif %}
    

{% if request.user.is_authenticated %}

<li class="nav-item"><a class="nav-link" href="{% url 'AboutUs' %}">Acerca de nosotros</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Contacto' %}">Contactanos</a></li>
<div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Hola, {{request.user}}
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
          {% if perms.postApp.add_post %}
          <li><a class="dropdown-item" href="{% url 'postLista' %}">Administrar Posts</a></li>
            {% endif %}
          <li><a class="dropdown-item" href="{% url 'PostsConMeGustaPropios' %}">Mi actividad | Me Gusta</a></li>
          <li><a class="dropdown-item" href="{% url 'EditarPerfil' %}">Editar Perfil</a></li>
          <li><a class="dropdown-item" href="{% url 'Logout' %}">Cerrar Sesión</a></li>
        </ul>
      </li>
    </ul>
  </div>
{% endif %}


{% endblock editNavBar %}

{% block logInLogOut %}

<style>
  body,
  html {
    margin: 0;
    padding: 0;
    height: 100%;
    background: #f3f6f7 !important;
  }
  .user_card {
    width: 850px;
    margin-top: auto;
    margin-bottom: auto;
    background: #9bc5a6;
    position: relative;
    display: flex;
    justify-content: center;
    flex-direction: column;
    padding: 10px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border-radius: 5px;

  }

  .form_container {
    margin-top: 20px;
  }

  #form-title{
    color: #fff;
    
  }
      .form input {
          width: 90%;
          height: 30px;
          margin: 0.5rem;
      }
  .login_btn {
    width: 100%;
    background: #282929 !important;
    color: white !important;
  }
  .login_btn:focus {
    box-shadow: none !important;
    outline: 0px !important;
  }
  .login_container {
    padding: 0 2rem;
  }
  .input-group-text {
    background: #666666 !important;
    color: white !important;
    border: 0 !important;
    border-radius: 0.25rem 0 0 0.25rem !important;
  }
  .input_user,
  .input_pass:focus {
    box-shadow: none !important;
    outline: 0px !important;
  }

  #messages{
    background-color: grey;
    color: #fff;
    padding: 10px;
    margin-top: 10px;
  }
</style>


</head>

{% if user.is_authenticated %}

  <body>
  <div class="container h-100">
    <div class="d-flex justify-content-center h-100">
      <div class="user_card">
        <div class="d-flex justify-content-center">
          <h3 id="form-title">{{tipo_template}} post</h3>
        </div>
        <div class="d-flex justify-content-center form_container">
          <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div class="input-group-append">
                  </div>
                    {{form.as_p}}
                </div>
            <div class="d-flex justify-content-center mt-3 login_container">
              <button type="submit" class="btn btn-primary">Publicar comentario</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  </body>
{% else %}

  <div class="alert alert-warning" role="alert">
    Inicia sesión para poder comentar algo!. <a href="{% url 'Login' %}" class="alert-link">Iniciar Sesión</a>. Ahí encontraras el boton para poder registrarte tambien.
  </div>

{% endif %}

{% endblock logInLogOut %}

templates/postApp/contacto.html
<!DOCTYPE html>
<html lang="en">
<head>

    
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
				 </ul>
			</div>
		</div>
	</nav>

    <title>Contacto</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contacto</title>
</head>
<body>
    <hr/>

    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #f3f6f7 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #9bc5a6;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #282929 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #666666 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

    <center>
        <p1>Hola, puedes contactarnos a través del siguiente formulario:</p1>
        <hr/>
        </p>
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Enviar</button>
</form>
    </center>
    
</body>
</html>

templates/postApp/inicio.html
{% extends 'index.html' %}

{% block barraBusqueda %}

<div class="row" style="width: 400px">
  <div class="col-md-12 search">
    <form method="get">
        <div id="custom-search-input">
          <div class="input-group col-md-12">
            <input type="text" class="form-control" style="height: 29px" placeholder="Buscar..." name="buscar" value = "{{ request.GET.buscar }}">
            <span class="input-group-list">
              <i class="icon icon-search"></i>
              <button type="submit" class="boton btn-success">Buscar</button>
            </span>
          </div>
        </div>
    </form>
  </div>
</div>

{% endblock barraBusqueda %}


{% block bienvenido %}

<h1 class="fw-bolder">¡Bienvenido al Blog CoderHouse</h1>
<p class="lead mb-0">El sitio web en donde encontrarás todo lo relacionado al mundo IT</p>


{% endblock bienvenido %}




{% block editNavBar %}


{% if not request.user.is_authenticated  %}

<li class="nav-item"><a class="nav-link" href="{% url 'AboutUs' %}">Acerca de nosotros</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Contacto' %}">Contactanos</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Login' %}">Ingresar</a></li>
    
{% endif %}
    

{% if request.user.is_authenticated %}

<li class="nav-item"><a class="nav-link" href="{% url 'AboutUs' %}">Acerca de nosotros</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'Contacto' %}">Contactanos</a></li>
<div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Hola, {{request.user}}
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            {% if perms.postApp.add_post %}
          <li><a class="dropdown-item" href="{% url 'postLista' %}">Administrar Posts</a></li>
            {% endif %}
          <li><a class="dropdown-item" href="{% url 'PostsConMeGustaPropios' %}">Mi actividad | Me Gusta</a></li>
          <li><a class="dropdown-item" href="{% url 'EditarPerfil' %}">Editar Perfil</a></li>
          <li><a class="dropdown-item" href="{% url 'Logout' %}">Cerrar Sesión</a></li>
        </ul>
      </li>
    </ul>
  </div>

{% endif %}

{% endblock editNavBar %}


{% block logInLogOut %}
    
<h1>{{mensaje}}</h1>

{% endblock logInLogOut %}

{% block backgroundImage %}

<div
    class="bg-image"
    style="
    background-image: url('/static/css/images/Blog-Post_thumbnail.png');
    height: 70vh;
    "
></div>

{% endblock backgroundImage %}


{% block blockPosts %}
  
{% for p in posts %}
<div class="container">
  <div class="row mb-2">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
          <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-primary">{{ p.categoria }}</strong>
              <h3 class="mb-0">{{ p.titulo }}</h3>
              <div class="mb-1 text-muted">{{p.fecha_publicacion}}|{{p.autor}}</div>
              <p class="card-text mb-auto">{{ p.subtitulo }}</p>
                <span><i class="fa-regular fa-thumbs-up"></i> {{ p.likes.count }}</span>
                <span><i class="fa-regular fa-comments"></i> {{ p.get_comentarios_count }}</span>
                
            <a href="{% url 'verPost' p.id %}">Ver post</a>
        </div>
      <div class="col-auto d-none d-lg-block">
          <img src="{{ p.imagen.url }}" width="250" height="250">
      </div>
    </div>
  </div>    
</div> 
{% endfor %}

<hr><br><br>
            <!-- Pagination-->
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
            <li class="page-item"><a class="page-link" href="?pagina=1">&laquo Primer página</a></li>
            <li class="page-item"><a class="page-link" href="{% url 'inicio' %}?pagina={{posts.previous_page_number}}">Página anterior</a></li>
            {% endif %}
            

            
            {% for n in numeros  %}
            <li class="page-item"><a class="page-link" href="?pagina={{forloop.counter}}">{{forloop.counter}}</a></li>
            {% endfor %}
              
            <!--
            <li class="page-item disabled"><a href="#" class="page-link">Páginas: {{posts.number}} de {{posts.paginator.num_pages}}</a></li>
            -->
            
            
            {% if posts.has_next %}            
            <li class="page-item"><a class="page-link" href="{% url 'inicio' %}?pagina={{posts.next_page_number}}">Página siguiente</a></li>
            <li class="page-item"><a class="page-link" href="?pagina={{posts.paginator.num_pages}}">Última página&raquo</a></li>
            {% endif %}
              </ul>
            </nav>
<hr>
{% endblock blockPosts %}

templates/postApp/post_confirm_delete.html
{% extends 'index.html' %}

    {% block blockPosts %}
        {% if user.is_authenticated %}
                <div class="container">
                    <h1>
                        ¿Seguro quieres eliminar este post?
                    </h1>
                    <form method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Si, quiero eliminarlo</button>

                    </form>
                </div>
                {% else %}

                <div class="alert alert-warning" role="alert">
                    Debes iniciar sesion para realizar cambios. <a href="{% url 'Login' %}" class="alert-link">Iniciar Sesión</a>. Ahí encontraras el boton para poder registrarte tambien.
                </div>
        {% endif %}

    {% endblock blockPosts %}